wantedly/apig

.gitignore, README.md, glide.lock, glide.yaml
To manage dependencies in a consist way, and fix the revisions of all dependencies.
Introduce [glide](https://github.com/Masterminds/glide) for dependency management.
=> Introduce glide

_fixtures/models.go, parse.go, parse_test.go
To confirm & ensure the behavior of model parser.
Write test to check the behavior of model parser.
Fortunally I found a bug around parsing fields by writing test.
=> Write test of parse

Makefile, _fixtures/README.md, _fixtures/controllers/user.go, _fixtures/router/router.go, _templates/controllers/controller.go.tmpl, generator_test.go
We should ensure that generator generates all files correctly.
Write tests of methods of generator.
=> Write tests of generator

_templates/controller.go.tmpl, _templates/skeleton/db/pagination.go.tmpl, generator.go
To support pagination.
- Add template and generate it when ``apig new`` executed.
- Add pagination rogic to generated controllers.
=> Add pagination

_templates/skeleton/version/version.go.tmpl
- found a bug where I have implemented 
- when get the version from Accept-Header.
- fix bug
=> Fix bug header version

_templates/skeleton/helper/field.go.tmpl, generator.go, main.go, model.go, parse.go, parse_test.go
~~To resolve N+1~~
To prepare to support eager loading.
=> Add function returning model addition associate

_templates/controller.go.tmpl, generator.go, generator_test.go, model.go, testdata/controllers/user.go
To avoid N+1 problems, we have to fetch associations using preload.
And sometimes we would like to choose JSON fields to receive.
Generate controller with these logic.
=> Generate controller with preload & field selector logic

generator.go, main.go
To improve processing performance.
- `new` and `gen` subcommand generate file parallel.
- Remove hardcode template file name.
=> Parallel generate file

README.md
README example was confusing
Remove unneeded part
=> Change readme example simpler

apig/generate.go
At #31 I implemented converting to snake_case feature using the script on [Gist](https://gist.github.com/stoewer/fbe273b711e6a06315d19552dd4d33e6). From #37 I introduced [serenize/snaker](https://github.com/serenize/snaker) for conversion.
Use snaker packege instead of script on Gist.
=> Use snaker packege

_example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _templates/controller.go.tmpl, apig/testdata/controllers/user.go
Fix a sloppy error output in detail.
```
c.JSON(500, gin.H{"error": "error occured"})
```
```
c.JSON(400, gin.H{"error": err.Error()})
```
=> Fix error handling

README.md
README contains some typos and semantic/gramatically errors
Fix up these errors
=> Modify typos and semantic errors in README

_example/db/pagination.go, _templates/skeleton/db/pagination.go.tmpl
Fix a sloppy error output in detail.
```
if err != nil {
return db, errors.New("invalid parameter.")
}
```
```
if err != nil {
return db, err
}
```
=> Fix sloppy error handling

.travis.yml, Makefile, _example/README.md, _example/controllers/user.go, _example/db/db.go, _example/docs/company.apib, _example/docs/email.apib, _example/docs/index.apib, _example/docs/job.apib, _example/docs/profile.apib, _example/docs/user.apib, _example/router/router.go, apig/detail.go, apig/generate.go, apig/model.go, script/generation_test.sh, script/integration_test.sh
We already have some unit tests to check the below:
- Files are generated in appropriate location
- File body corresponds to the expected one
- Method returns the expected response
However, we also have to check the behavior of generator itself. Additionally, API server in `_example` should be maintained as the latest artifacts.
Add intergation test and run at CI. This test does:
0. Regenerate all files of API server in `_example` 
0. Check whether there is no diff between before and after
0. Try building API server and check whether build succeeds
⚠️ This pull request depends on changes in #53 . After merging #53 I'll update files of API server in `_example` and remove `[WIP]` flag.
=> Add generation test

_example/db/pagination.go, _example/version/version.go, _templates/skeleton/db/pagination.go.tmpl, _templates/skeleton/version/version.go.tmpl, script/generation_test.sh
Some code does not adapt to Golang naming convention. 
Make cosmetic changes in pagination.go and version.go
=> Cosmetic changes of pagination / version

README.md
Currently there is no documentation about generated API server. It is difficult to understand the behavior of API server at once.
Write API server specification
=> Write API server specification

.travis.yml
Go 1.7 was just released.We need a support for new version.
=> Add GO 1.7 support

README.md, _example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _templates/controller.go.tmpl, apig/testdata/controllers/user.go
#60 
- if `?pretty==true`, formats JSON output.
- `:8080/users?pretty`
=> Formats json using ?pretty

README.md, _example/helper/field_test.go, _example/models/company.go, _example/models/email.go, _example/models/job.go, _example/models/profile.go, _example/models/user.go, _templates/skeleton/helper/field_test.go.tmpl, apig/testdata/models.go, apig/testdata/parse/models.go
Accepts `form` format request.
#65 
- Add `form:fieldname` tags to an existing model.
- Add the discription of `data type` in `readme.md`.
=> Accepts form format in example model.

_example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _templates/controller.go.tmpl, apig/testdata/controllers/user.go
- In Controller, improve some mistakes and insufficient error handlings.
1. Fix nil variables (Error)
- The `db.Create` error handling variable, `err` is uninitialized.
2. attaches the error handling to `c.Bind`.
- If request JSON body is broken , returns 400 status code.
3. attaches the error handling to `db.Save` and `db.Delete`.
- In the `gorm document`, they don't have the error handling, but I added just in case.
=> Improve the error handling propery

apig/generate.go
- Formats golang files generated by apig using `go/format` package.
=> Format golang files

_example/version/version.go, _example/version/version_test.go, _templates/skeleton/version/version.go.tmpl, _templates/skeleton/version/version_test.go.tmpl
#85 
- Check the number of c.Request.Header["Accept"]
- Update testdata
=> Check the number of `acceptheader` items

_templates/README.md.tmpl, _templates/controller.go.tmpl, _templates/index.apib.tmpl, _templates/model.apib.tmpl, apig/generate.go
- Sort the order of the field in alphabetical order.
- Convert lowercase to lowerCamelCase.
- Resource name in error message returns in the form of `snake_case`.
There is nothing with compound words to `_example` model, so I changed the only `.tmpl` file.
=> Refactor generator

_example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/root.go, _example/controllers/user.go, _templates/controller.go.tmpl, _templates/root_controller.go.tmpl, apig/testdata/controllers/root.go, apig/testdata/controllers/user.go
- Refactor the flow of `if` statement
- controller:`pretty`, `pagination`
- pagination: `c.Request.TLS`
- Insert lines and Adjust the position in each logic statement.
In order to avoid mistakes, I make this branch based on #92 branch.
After #92 , I rebase this branch to the master of that time. Sorry 🙇
=> Refactor controller

_example/db/db.go, _example/version/version.go, _templates/db.go.tmpl, _templates/skeleton/db/db.go.tmpl, _templates/skeleton/version/version.go.tmpl, apig/testdata/db/db.go
- Change the method of getting the accept header.
- Insert a line.
=> Refactoring

README.md, _example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _example/db/filter.go, _templates/controller.go.tmpl, _templates/skeleton/db/filter.go.tmpl, apig/testdata/controllers/user.go
- Filter fields in the response data.
- implement a `?q[field_name]` query.
- remove `?ids` query - This is almost the same query.
=> Filter fields

README.md, _example/main.go, _templates/skeleton/main.go.tmpl, apig/generate.go, apig/import.go, apig/import_test.go
- Change the value of the port in the environment variable `PORT`.
```
$ PORT=3000 bin/server
```
- Add the environment variable `PORT`.
- Except the `.` when get the import path.
=> Change port dynamically

_example/db/filter.go, _example/db/filter_test.go, _templates/skeleton/db/filter.go.tmpl, _templates/skeleton/db/filter_test.go.tmpl
=> Add filter testcase

README.md, _example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _example/db/sort.go, _example/db/sort_test.go, _templates/controller.go.tmpl, _templates/skeleton/db/sort.go.tmpl, _templates/skeleton/db/sort_test.go.tmpl, apig/testdata/controllers/user.go
- Sort parameters at the time of the database query.
- Add `?sort` query.
```
?sort=id,-age,created_at
```
- Minus prefix is descending order.
=> Sort parameters

_example/docs/company.apib, _example/docs/email.apib, _example/docs/job.apib, _example/docs/profile.apib, _example/docs/user.apib, _templates/model.apib.tmpl, apig/associate.go, apig/generate.go, apig/parse.go, apig/testdata/docs/user.apib
=> Refactor APIBluerprint

_example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _example/db/db.go, _example/db/filter.go, _example/db/pagination.go, _example/db/parameter.go, _example/db/sort.go, _templates/controller.go.tmpl, _templates/db.go.tmpl, _templates/skeleton/db/db.go.tmpl, _templates/skeleton/db/filter.go.tmpl, _templates/skeleton/db/pagination.go.tmpl, _templates/skeleton/db/parameter.go.tmpl, _templates/skeleton/db/sort.go.tmpl, apig/testdata/controllers/user.go, apig/testdata/db/db_postgres.go, apig/testdata/db/db_sqlite.go
After #111  , be able to merge this PR.
- Pagination header links is outdated since `apig` added queries.
- Add struct `Parameter`
- Organize to the url parameter for db.
- Update pagination header links.
=> Organize the structure to the url parameter for db
