.gitignore, Makefile, README.md
To install dependencies and build binaries easily and simply.
Write `Makefile` to integrate build process.
=> Prepare Makefile

Makefile, README.md, _examples/simple/controllers/user.go, _examples/simple/controllers/user_test.go, _examples/simple/main.go, _examples/simple/router/router.go, _examples/simple/server/server.go, glide.lock, glide.yaml
Close #5
`api-server-generator` is too long to type.
Shorten the command and application name: `api-server-generator` -> `apig`
After merged this, we have to rename this repository name too.
=> Rename application name to apig

_templates/controller.go.tmpl
Close #10 
Conflict between package name and variable.
Define alias for db package.
```
package controllers
import (
"net/http"
dbpkg "github.com/munisystem/hoge/db"
"github.com/munisystem/hoge/models"
"github.com/gin-gonic/gin"
)
func GetUsers(c *gin.Context) {
db := dbpkg.DBInstance(c)
fields := c.DefaultQuery("fields", "*")
var users []models.User
db.Select(fields).Find(&users)
c.JSON(200, users)
}
```
=> Define alias for db package

.gitignore
Binary built by simple `go build` should not be included in Git repository.
Add `apig` to `.gitignore`. I missed this modification at #15 .
=> Do not track apig binary

Makefile, README.md
from #25
Current build process does not follow the usual way. Is `make deps` really needed?
```bash
$ make deps
$ make 
```
Do `make deps` in default `make` target internally.
After applying this patch, we can build binary more simply:
```bash
$ make
```
=> Do fetching deps and building binary simultaneously

_templates/skeleton/version/version.go.tmpl
When we test the usability, this strict version check prevents api call by browser.
So we concluded such strictness is needless for apig.
Remove version header check
cc @shimastripe
=> Remove version header check

_templates/controller.go.tmpl
We do not always have to preload all associations.
If no field is specified or primitive fields are specified, server returns JSON without preloads.
If association field is specified, do preload once and return JSON.
=> Reduce preloads

_templates/router.go.tmpl, generator.go, generator_test.go
Now we just convert all chars in model name to lower case for filename and endpoint. However this is not suitable for multi-word model name.
For example, from `AccountName` model , `accountname.go` and `/api/accountname/` endpoint are generated.
Convert model name to snake_case for filename and endpoint.
For example, from `AccountName` model , `account_name.go` and `/api/account_name/` endpoint are generated.
`toSnakeCase` function is originated in https://gist.github.com/stoewer/fbe273b711e6a06315d19552dd4d33e6 .
=> Convert model name to snake_case for filename

_templates/db.go.tmpl, generator.go, main.go
For easy to use.
Add auto migration rogic to ``db/db.go``
```
>>> AUTOMIGRATE=true go run main.go
```
=> Support automigrate

main.go
To solve #25 
```
apig new apig-sample
create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/README.md
create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/.gitignore
create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/main.go
create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/db/db.go
create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/db/pagination.go
create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/router/router.go
create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/middleware/set_db.go
create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/server/server.go
create /Users/awakia/src/github.com/Naoyoshi Aikawa/apig-sample/helper/field.go
create /Users/awakia/src/github.com/Naoyoshi …
```
=> Solider parse of github username

_templates/controller.go.tmpl, _templates/db.go.tmpl, _templates/skeleton/db/db.go.tmpl, generator_test.go, glide.lock, glide.yaml, testdata/controllers/user.go, testdata/db/db.go
Now we fix the depth of preload to 2. We would like to fetch no nested fields by default, and specify the depth of preload as we like.
Add new request parameter `preloads` to specify tables to do preload. `fields` parameter is used for choosing fields including in response JSON only.
- If `preloads` parameter is empty, server does not do any preloads.
- `preloads` parameter should be comma-separated string with snake_case table name. Nested tables should be connected with dot. e.g. `profile`, `profile.nation`, `profile.nation,account_name`
Currently we does not specify deeply-nested fields at `fields` parameter (e.g. `profile.nation.name`), but I'll fix this at another branch.
These examples show the behavior with new parameters. …
=> Define preload scope dynamically

apig/skeleton.go
Currently `apig new` tries to copy all files in `_templates/skeleton`, even if there are redundant files, such as `.DS_Store` and `#version.go.tmpl#`. It causes panic error at processing templates.
Copy files with extension `.tmpl` only.
=> Generate skeleton from .tmpl files only

.gitignore, _example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _templates/controller.go.tmpl, apig/testdata/controllers/user.go
When accessing to `GET /users/` endpoint and there is no user record, API server returns `null` instead of `[]`. This is not an appropriate response.
Return `[]` if there is no records.
=> Return empty array if there is no record

_example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _templates/controller.go.tmpl, apig/testdata/controllers/user.go
When iterating map, this style is redundant.
```go
for key, _ := range users {
fieldMap = append(fieldMap, helper.FieldToMap(users[key], fields))
}
```
Use better and more Go-ish style.
```go
for _, user := range users {
fieldMap = append(fieldMap, helper.FieldToMap(user, fields))
}
```
=> Take better way to iterate map

_templates/skeleton/server/server.go.tmpl
Indent in Go code should be hard-tab. However, generated `server.go` have soft-tab indents.
Modify indent in `server.go`
=> Modify indent in server.go

_example/db/db.go, _templates/db.go.tmpl, apig/testdata/db/db.go
`AUTOMIGRATE=TRUE` is unusual way for specifying boolean option.
If `AUTOMIGRATE=1` is passed, do database migration.
=> Accept AUTOMIGRATE=1 only

_example/controllers/user.go, _example/helper/field.go, _example/helper/field_test.go, _templates/skeleton/helper/field.go.tmpl, _templates/skeleton/helper/field_test.go.tmpl
Generated API server can specify fields to fetch by `fields` query parameter. However, in reality, SQL query still tries to fetch ALL fields.
Regardless of `fields` query parameter, the SQL query below is always executed.
```sql
SELECT * FROM tables ...
```
This means that DB performance haven't been improved yet.
Narrow fields dynamically along with `fields` query parameter.
For example...
| `?fields=` | SQL query |
|---|---|
| none | `SELECT *` |
| `fields=id` | `SELECT id` |
| `fields=id,name` | `SELECT id,name` |
| (belongs-to) `fields=user.name` | `SELECT user_id` |
| (has-one) `fields=profile.engaged` | `SELECT id` |
| (has-many) `fields=emails.address` | `SELECT id` |
Non-exist fields are omitted.
=> Narrow fields in SQL query

apig/generate.go, apig/parse.go, apig/parse_test.go, apig/testdata/parse/models.go, apig/testdata/parse/router.go
When user executes `apig gen --all` at application repository, API namespace always rewrite as `""` (empty string).
Extract namespace from existing `router/router.go` and rewrite with it.
This is another and better approach of #53 .
=> Extract API namespace from router at gen command

README.md, command/gen.go, command/new.go
Close #61 
`-v` option is now used for showing CLI version.
Unbind `-v` from VCS option and use `--vcs` only.
=> Unbind -v from VCS option

_example/helper/field.go, _example/helper/field_test.go, _templates/skeleton/helper/field.go.tmpl, _templates/skeleton/helper/field_test.go.tmpl
If response data contains null, currently response JSON also contains null.
If `omitempty` tag is specified in field definition, exclude the null field from the response.
This feature is enabled when user tries to fetch all fields (`*`). When some fields are specified in `?fields=` parameter, response JSON contains the fields even if they are null.
Before implementing this feature, I added some test for existing `FieldToMap` method.
=> Consider omitempty option

README.md
At first, simple `go get github.com/wantedly/apig` fails due to lack of go-bindata. Additionally, we cannot build generated API server from scratch.
Write how to download this repository and how to download dependencies of API server.
=> Update README how to install and build

_templates/README.md.tmpl, apig/generate.go, apig/generate_test.go, apig/testdata/README.md
Now API namespace can be changed by user.
Change API namespace in README dynamically.
=> Write API namespace in README dynamically

_example/controllers/root.go, _example/router/router.go, _templates/root_controller.go.tmpl, _templates/router.go.tmpl, apig/generate.go, apig/generate_test.go, apig/testdata/controllers/root.go, apig/testdata/parse/router.go, apig/testdata/router/router.go
Close #64 
Currently, root endpoint 'http://example.com/' return empty and `404 Not Found`. This behavior is not so good especially for newcomers.
Like https://api.github.com/ , let API server return all available API endpoints.
Here is example:
```bash
$ curl localhost:8080
{
"companies_url": "://localhost:8080/companies",
"company_url": "://localhost:8080/companies/{id}",
"email_url": "://localhost:8080/emails/{id}",
"emails_url": "://localhost:8080/emails",
"job_url": "://localhost:8080/jobs/{id}",
"jobs_url": "://localhost:8080/jobs",
"profile_url": "://localhost:8080/profiles/{id}",
"profiles_url": "://localhost:8080/profiles",
"user_url": "://localhost:8080/users/{id}",
"users_url": "://localhost:8080/users"
}
```
=> Return the list of endpoints from top page

apig/parse.go, apig/parse_test.go, apig/testdata/parse/models.go
Close #71
Current apig is based on that all fields are tagged with `json`. So if no tag is provided, `apig new` and `apig gen` fails with panic.
If no tag is provided, use Go-struct field name as JSON key.
=> User field name as JSON key if no tag is provided

_example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _templates/controller.go.tmpl, apig/testdata/controllers/user.go
Few weeks ago, I introduced the feature to narrow fields in SQL query (https://github.com/wantedly/apig/pull/57). However, I missed to update controller template at the time. At #56 I overwrote all example files with code which omitted the feature, so now this feature is NOT enabled in generated API server.
Update controller template to narrow fields rightly and re-introduce this feature.
=> Narrow fields to retrive again

_example/helper/field.go, _example/helper/field_test.go, _templates/skeleton/helper/field.go.tmpl, _templates/skeleton/helper/field_test.go.tmpl
`omitempty` tag causes a panic in some types of field.
- int, string, ...
The reason is that `reflect.value.isNil()` cannot use these types.
Add `isEmptyValue` method.
=> `omitempty` tag causes a panic

_example/controllers/root.go, _templates/root_controller.go.tmpl, apig/generate.go, apig/testdata/controllers/root.go
- Generate `_templates/root_controller.go.tmpl`.
- Fix the url schema in endpoint lists from the blank `""` to  `"http" or "https"`.
=> Generate root controller

msg/msg.go
in `apig gen command`, `%!s(MISSING)` appeared.
```
[create /Users/takagi_go/go/src/github.com/shimastripe/fieldsquery/README.md aaa] %!s(MISSING)
```
Pass the expanded slice to the function.
=> Passing arguments to ... parameters

_example/helper/field.go, _templates/skeleton/helper/field.go.tmpl
- fields query cause a panic.
```
&fields=emails.id
```
- Check the Type of the items in the Array
=> Confirm the type in the array

_example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _example/helper/field.go, _templates/controller.go.tmpl, _templates/skeleton/helper/field.go.tmpl, apig/testdata/controllers/user.go
- fields query cause a panic and unpleasant behaviors.
Current status is as follows.
1. When the nest of the source is not a structure, panic occurs.
```
?fields=id.id
```
1. When specify a nonexistent field, it is ignored.
```
?fields=id,hogehoge
```
```json
[
{
"id": 1
}
]
```
1. It should return error if nest query is specified in spite of the structure is null.
```go
User{
AccountName: null,
}
```
```
?fields=account_name.id
```
```json
[
{
"account_name": null
}
]
```
1. Checked the type of argument.
2. Checked the specified field whether it exists in the structure.
3. Checked whether the structure and the specified field is null or not.
=> fields query cause panic.

_example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _example/db/pagination.go, _templates/controller.go.tmpl, _templates/skeleton/db/pagination.go.tmpl, apig/testdata/controllers/user.go
Struct `pagination` has `pointer` receivers. 
This method may cause panics if this function is called without being initialized.
- Add error handlings.
- Check `http` or `https` in pagination link.
=> Add pagination error handling

apig/generate.go
Try again #67 
Now `generate.Generate` function has [167 lines](https://github.com/wantedly/apig/blob/master/apig/generate.go#L389-L556). This is so fat and its logic is complex.
Additionally, it seems that there are some unnecessary goroutines.
Extract some logic to another funcitons. Lines are reduced up to 90 lines.
Remove unnecessary goroutines.
=> Refactor generate.Generate function (again)

README.md, _example/controllers/company.go, _example/controllers/email.go, _example/controllers/job.go, _example/controllers/profile.go, _example/controllers/user.go, _templates/controller.go.tmpl, apig/testdata/controllers/user.go
- Using `?stream` parameter, return JSON objects in streaming format.
ref.) https://en.wikipedia.org/wiki/JSON_Streaming
- Line delimited JSON format.
```
{"account_name":null,"created_at":"2016-09-12T17:27:36.135532037+09:00","emails":null,"id":1,"name":"test1","updated_at":"2016-09-12T17:27:36.135532037+09:00"}
{"account_name":null,"created_at":"2016-09-12T17:27:37.353012323+09:00","emails":null,"id":2,"name":"test2","updated_at":"2016-09-12T17:27:37.353012323+09:00"}
{"account_name":null,"created_at":"2016-09-12T17:27:38.194750274+09:00","emails":null,"id":3,"name":"test3","updated_at":"2016-09-12T17:27:38.194750274+09:00"}
```
=> Return JSON objects in streaming format

_example/helper/field_test.go, _templates/skeleton/helper/field_test.go.tmpl
#89 
`func FieldToMap(model interface{}, fields map[string]interface{}) (map[string]interface{}, error)` 
return a second value for error handling.
But, testcase did not correspond to it.
Testcase correspond to it.
=> Update field testcase

_templates/index.apib.tmpl
If model name is composited by multiple words, incorrect hyperlink is generated in API blueprint index page.
for example: company_page model -> link to ❌  `companypage.apib` ⭕ `company_page.apib`
Generate correct link to model API blueprint page
=> Modify API Blueprint link to appropriate one

_example/db/filter.go, _example/db/pagination.go, _example/db/sort.go, _example/middleware/set_db.go, _example/server/server.go, _templates/skeleton/db/filter.go.tmpl, _templates/skeleton/db/pagination.go.tmpl, _templates/skeleton/db/sort.go.tmpl, _templates/skeleton/middleware/set_db.go.tmpl, _templates/skeleton/server/server.go.tmpl
ref.) https://astaxie.gitbooks.io/build-web-application-with-golang/content/ja/02.3.html#import
http://jinzhu.me/gorm/database.html#connecting-to-a-database
The blank import is used to initialize. `Gorm` also uses it in order to connect each databases.
- Remove blank imports except connecting to the database.
=> Remove unnecessary imports

_templates/db.go.tmpl, _templates/skeleton/db/db.go.tmpl, apig/testdata/db/db_postgres.go
`path/filepath` library is required by `sqlite` library. However, API server still imports `path/filepath` even if DB engine is PostgreSQL.
Do not import `path/filepath` when DB engine is PostgreSQL.
=> Omit path/filepath when DB engine is PostgreSQL

apig/skeleton.go
Similar to #94, `skeleton.go` has unnecessary goroutine out of loop.
In addition, regular expression is compiled at every time of calling `generateSkeleton`.
Remove unnecessary goroutine, store regexp in global variable to be cached.
=> Refactor skeleton

README.md
There are miss spells of "retrieve" in README.
Modify these miss spells.
=> Fix typo retrive -> retrieve

msg/msg.go
Generation of controllers, documents, and so on are running concurrently. Due to this, some of output messages are collapsed.
```
create /Users/dtan4/src/github.com/dtan4/api-server/controllers/user.go
create /Users/dtan4/src/github.com/dtan4/api-server/docs/compant.apib
create /Users/dtan4/src/github.com/dtan4/api-server/docs/job.apib
create  create /Users/dtan4/src/github.com/dtan4/api-server/controllers/company.go
create /Users/dtan4/src/github.com/dtan4/api-server/controllers/job.go
/Users/dtan4/src/github.com/dtan4/api-server/controllers/email.go
create /Users/dtan4/src/github.com/dtan4/api-server/controllers/occupation.go
create /Users/dtan4/src/github.com/dtan4/api-server/docs/recipe.apib
create /Users/dtan4/src/github.com/dtan4/api-server/docs/project.apib
create …
```
=> Use mutex for message output

_templates/skeleton/db/db.go.tmpl, apig/generate.go, apig/skeleton.go
- database name, `sqllite, postgres` is missing.
```go
import (
"github.com/jinzhu/gorm"
_ "github.com/jinzhu/gorm/dialects/"
)
```
- Function `generateDB` needs `detail.Database`. So call function `detectDatabase` when `apig gen` runs.
- Format skeleton template files.
=> DB name is missing

apig/generate.go
`collectModels` function causes conflict.
Lock the relevant section.
=> [Bug]Synchronize collectModels func
